name: 'aggregate_ticket_service'

services:
  
  domic.aggregate.ticket.api:
    networks:
      - domic
    image: aggregate_ticket_service_api_image:1.0.0
    container_name: "aggregate_ticket_service_api"
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "6100-6110:443"
    volumes:
      - log:/app/CoreLogs
      - ~/services/Domic-AggregateTicketService/.https/:/https/
    environment:
      - Elastic-Host=http://domic.elastic.search:9200
      - Elastic-Index=aggregateticket
      - Elastic-Username=domic
      - Elastic-Password=Domic123!@#
      - E-RabbitMQ-Host=domic.rabbit.mq
      - E-RabbitMQ-Port=5672
      - E-RabbitMQ-Username=domic
      - E-RabbitMQ-Password=Domic123!@#
      - I-RabbitMQ-Host=
      - I-RabbitMQ-Port=
      - I-RabbitMQ-Username=
      - I-RabbitMQ-Password=
      - E-RedisConnectionString=domic.redis:6379
#     - I-RedisConnectionString=domic.aggregate.ticket.redis:6379
      - I-RedisConnectionString=domic.redis:6379
      - MongoConnectionString=
      - C-SqlServerConnectionString=Server=
#     - Q-SqlServerConnectionString=Server=domic.aggregate.ticket.query.sql.server,1433;Database=AggregateTicketService;User ID=sa;Password=Domic123!@#;Persist Security Info=True;MultipleActiveResultSets=True;
      - Q-SqlServerConnectionString=Server=domic.sql.server,1433;Database=AggregateTicketService;User ID=sa;Password=Domic123!@#;Persist Security Info=True;MultipleActiveResultSets=True;
      - Host=domic.aggregate.ticket.api
      - Port=80
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Domic123!@#
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Domic.WebAPI.pfx
    
#    depends_on:
#      - domic.aggregate.ticket.query.sql.server
#      - domic.aggregate.ticket.redis
  
#  domic.aggregate.ticket.query.sql.server:
#    networks:
#      - domic
#    image: 'mcr.microsoft.com/mssql/server'
#    container_name: "aggregate_ticket_query_sql_server"
#    ports:
#      - 1404:1433
#    environment:
#      - ACCEPT_EULA=Y
#      - SA_PASSWORD=Domic123!@#
#
#  domic.aggregate.ticket.redis:
#    networks:
#      - domic
#    image: 'redis'
#    container_name: 'aggregateticket_redis'
#    command: 'redis-server'
#    ports:
#      - 7080:6379

volumes:
  log:
    
networks:
  domic:
    external: true